// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default {
  mySidebar: [
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        title: "All Guides",
        slug: "/category/guides",
        description: "Explore our documentation guides",
      },
      items: [
        "guide/intro",
        {
          type: "category",
          label: "Advanced",
          collapsed: true,
          items: ["guide/advanced/topic1", "guide/advanced/topic2"],
        },
      ],
    },
    {
      type: "link",
      label: "Community",
      href: "https://discord.gg/docusaurus",
    },
  ],
};
